# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c30ba2e6e7095f6d152c185ac0512b87643e3e19dd4096a7291aaca9f30d1589d849a2fbf250c6283589c76e033aa84ba5909ee2166babe5314503374821ac

test:
  secret_key_base: 5e74aed8b0c63b3d6047d8d02dd3313580ecb387056a19534603980c5efad9c7b9baae962e799e31aabe83ce4e98c1487d8a6cf5243a77b7acf4f982b48c4792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
